<a href="https://colab.research.google.com/github/JoanWaweru/AI-ML-Group-Task/blob/main/ANN_Scratch_ICS_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np

In [ ]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [ ]:
batch_size=2

Dataset

In [ ]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
      'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [ ]:
dataset=pd.DataFrame(data)

In [ ]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [ ]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [ ]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [ ]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [ ]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [ ]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [ ]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [ ]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [ ]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [ ]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [59]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [60]:
weight_1

array([[ 0.54243399,  0.06538203],
       [ 0.09962462,  0.12095005],
       [-0.37562006,  0.00987398]])

In [ ]:
weight_2[0][0]


0.3263840948993233

In [ ]:
X_norm[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [ ]:
output_1=X_norm[0:batch_size]@weight_1
output_1

array([[-0.60323487,  1.14579467],
       [-0.66912165,  0.63731765]])

In [ ]:
act_output=sigmoid(output_1).numpy()
act_output

array([[0.35360396, 0.75874196],
       [0.33869355, 0.65414686]])

In [ ]:
pred_output=act_output@weight_2
pred_output=np.reshape(pred_output,(1,-1))
pred_output

array([[0.08127137, 0.08111107]])

Mean Squared Error

In [ ]:
y_true=y_norm[0][0:batch_size]
y_pred=pred_output

In [ ]:
y_pred[0][1]

0.0811110739282442

In [ ]:
y_true

array([0.28571429, 0.21428571])

In [ ]:
mse(y_true,y_pred).numpy()

array([0.02976619])

Back Propagation

In [ ]:
y1 = y_true[0]
y1

0.2857142857142857

In [ ]:
y2 = y_pred[0][0]
y2

0.08127137419971227

In [ ]:
output=y1-y2
output

0.20444291151457344

Error Computation

In [ ]:
output2 = y2*(1-y2)
output2

0.0746663379354026

In [ ]:
error_k = output * output2
error_k

0.015265003519644752

Error of hidden Layers
𝑬𝒓𝒓𝒐𝒓(𝒋) = 𝒆𝒓𝒓𝒐𝒓 𝒂𝒕 𝒌 ∗ 𝒘𝒆𝒊𝒈𝒉𝒕 𝒐𝒇 𝒘𝒋𝒌 ∗ 𝒇’(𝒙𝒋)

In [ ]:
error_j = error_k * weight_2[0][0] * (y_pred[0][0] * (1-y_pred[0][0]))
error_j

0.0003720066875293302

In [ ]:
error_i = error_k * weight_2[1][0] * (y_pred[0][1] * (1-y_pred[0][1]))
error_i

-5.119187147748561e-05

Delta rule: 𝑊𝑛𝑒𝑤 = 𝑊𝑐𝑢𝑟𝑟𝑒𝑛𝑡 + Δ𝑊𝑐𝑢𝑟𝑟𝑒𝑛t

In [ ]:
n = uniform(0,1)
n

0.24011304343691342

In [ ]:
w_new_j = weight_2[0][0] + (n * error_k * y_pred[0][0])
w_new_j

0.3266819810170636

In [ ]:
w_new_i = weight_2[1][0] + (n * error_k * y_pred[0][1])
w_new_i

-0.044697356703819566

In [61]:
weight_1

array([[ 0.54243399,  0.06538203],
       [ 0.09962462,  0.12095005],
       [-0.37562006,  0.00987398]])

In [63]:
output_1

array([[-1.59792438, -0.48145644],
       [-1.53738029,  0.25931379]])

In [74]:
 weight_1[2:3]

array([[-0.37562006,  0.00987398]])

Calculating weights for the first layer

In [82]:
w_new_1 = weight_1[0:1] + (n * error_j * output_1[0:1])
w_new_1

array([[0.54253351, 0.06541201]])

In [81]:
w_new_2 = weight_1[1:2] + (n * error_j * output_1[1:2])
w_new_2

array([[0.09972037, 0.1209339 ]])

In [80]:
weight_1

array([[ 0.54243399,  0.06538203],
       [ 0.09962462,  0.12095005],
       [-0.37562006,  0.00987398]])

In [79]:
w_new_3 = weight_1[2:3] + (n * error_j * output_1[0:2])
w_new_3[0:1]

array([[-0.37552054,  0.00990397]])

In [84]:
weight_1_update = np.concatenate((w_new_1, w_new_2, w_new_3[0:1]))
weight_1_update

array([[ 0.54253351,  0.06541201],
       [ 0.09972037,  0.1209339 ],
       [-0.37552054,  0.00990397]])